### ISSUE TITLE
Chrome: Query Monitor not shown in dev tools

### ISSUE THREAD

**Issue by tyrann0us** [Mte90/WP-Query-Monitor#6]
After installing the extension and restarting Chrome, there's still no new tab in the DevTools. Does this extension actually work in Chrome? If so, where exactly is it supposed to show up in the DevTools? It would be helpful to add screenshots to the [Chrome Web Store](https://chrome.google.com/webstore/detail/wordpress-query-monitor/balkncdjmlkelndfkmgcaclmfkdgpdjg).
Thanks!

Windows v10.0.17134 Build 17134
Chrome v67.0.3396.99
WordPress Query Monitor v0.2.0

**Comment by Mte90** [comment]
I am suing without problems on Firefox, I have to check better on Chrome.
The problem of screenshot that on Chrome Store require mandatory size instead on Firefox there aren't this kind of problems but I will check that.

**Comment by tyrann0us** [comment]
Perfect, https://github.com/Mte90/WP-Query-Monitor/commit/996cd58dc79a87031b46bf0b5153e61dd593b5de did it!
